spring:
  application:
      name: eureka-server
server:
  port: 9999

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---
spring:
  profiles: peer1
  application:
      name: eureka-server1
server:
  port: 8762
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server2
server:
  port: 8761
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
