spring:
  application:
    name: config-server
#  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev
#      lable: master
#      server:
#        git:
#          uri: https://gitee.com/mxzenfyx/fastjee-config-repo
#          username: 93839187@qq.com
#          passoword: 810314yx
#          searchPaths:
server:
  port: 6666
eureka:
  instance:
    hostname: peer2
    # 更改eureka更新频率, 关闭eureka的自我保护机制.
    leaseRenewalIntervalInSeconds: 5 # 租期更新时间间隔(默认30秒)
    leaseExpirationDurationInSeconds: 20 # 租期到期时间(默认90秒)
  client:
    serviceUrl:
      defaultZone: http://fastjee-registration.com:5000/eureka/
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
logging:
  config: classpath:logback.xml
---
spring:
  profiles: zuul
  application:
#    name: feign-consumer
    #      name: ribbon-consumer
    name: zuul-gateway
server:
  port: 9997
zuul:
  routes:
    api-gateway:
      path:
        /api/**
      serviceId:
        HELLO-SERVICE
#      url:
#        http://127.0.0.1:9998
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://peer1:8762/eureka/,http://peer2:8761/eureka/
---
spring:
  profiles: peer1
  application:
      name: eureka-server1
server:
  port: 8762
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server2
server:
  port: 8761
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
